### PR TITLE
Manually depacked Jabo's DirectSound plugin.

### PR DESCRIPTION
**Pull request by mountnside**
Might need some imports or exports fixed. Mainly to do with the antitamper used on 1.7 and its plugins.

Very easy to depack, just find the OEP jump from UPX land.

### CODE REVIEW

**Comment by DerekTurtleRoe** [comment]
Oh, thanks! I hadn't seen your PR since GitHub seems to only give me notifications when it feels like it.

Do you know what exact anti-tamper was used or is that still up in the air?

**Comment by mountnside** [comment]
The antitamper is custom made.

**Comment by DerekTurtleRoe** [comment]
OK, interesting. Thanks for doing this though!

**Comment by mountnside** [comment]
No problem.

Can't make promises, but it would be nice at least to do some more debugging on these.

**Pull request merged**
